### ISSUE TITLE
Can't implement events with pixi.js v6 and typescript

### ISSUE THREAD

**Issue by jkukuryk** [pixijs/pixijs#7753]
### Expected Behavior
can add events listeners or on function to containers

### Current Behavior
Can't implement any pointer events

### Possible Solution
Don't know
### Environment
pixi.js v. 6.1.2
@pixi/events
Chrome / Windows

I try to make jsFidle but PIXI.min.js can't load:
https://jsfiddle.net/jkukuryk/js5zwfdq/37/

**Comment by ShukantPal** [comment]
You should probably use @pixi-essentials/svg 😀

**Comment by mdudek** [comment]
I have found following issues with TS typings:

1. Missing properties 'name', 'interactive', 'buttonMode' on DisplayObject and inherited classes.
2. Missing method 'addEventListener' on DisplayObject and inherited classes, even if I had imported '@pixi/events'

**Comment by ivanpopelyshev** [comment]
@mdudek need complete reproduction for that. something wrong with global mixins

**Comment by mdudek** [comment]
I have created simple reproduction project @ivanpopelyshev

[pixi_mixins_issue_reproduction.zip](https://github.com/pixijs/pixijs/files/7177566/pixi_mixins_issue_reproduction.zip)

**Comment by ivanpopelyshev** [comment]
Yes, mixins aren't working there , somehow.

btw, `sp.name` is from `@pixi/mixin-cache-as-bitmap` , but it doesnt work anyway :)

**Comment by ivanpopelyshev** [comment]
Obligatory post in case its stopping you from your work: use main `pixi.js` bundle for now, add `@pixi/events`, dont forget to install EventSystem. Hope you know that `@pixi/events` is new alternative interaction engine, not the default one.

This example is minimal to check for TS project, its not supposed to render anything  - i post this note, just in case people will take it and try to actually render :)

**Comment by mdudek** [comment]
The pixi.js npm package typings file (index.d.ts) is referencing typings from @pixi/* packages, so it does not help to resolve typescript errors.

**Comment by ivanpopelyshev** [comment]
It works in my projects. Therefore we have to know wtf is different with this example, whether our last pixi version is wrong, ts config, or something else :)

**Comment by bigtimebuddy** [comment]
These are three errors with this project @mdudek:

* Need to add `import '@pixi/mixin-get-child-by-name'` so that `name` is added correctly (also add package as dependency)
* Your tsconfig.json requires `"esModuleInterop": true` compiler options, this is required for PixiJS
* `buttonMode` is not a property enabled in events, this is interaction only (maybe we should add it?) just set `sp.cursor = 'pointer'` and this does the same thing.

Once I fixed these, I was able to build fine without errors.

**Comment by mdudek** [comment]
Thanks @bigtimebuddy, works like a charm...

**Comment by ivanpopelyshev** [comment]
oih right, wrong mixin :) i somehow referencd cache-as-bitmap instead of `@pixi/mixin-get-child-by-name` . I also confirm that `esModuleInterop` works!

**Comment by bigtimebuddy** [comment]
I think that's a wrap here, going to close this issue.

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy the issue was opened by @jkukuryk  and wasnt solved. @mdudek problem is separate :)

**Comment by bigtimebuddy** [comment]
The problem here is that pixi-svg has a peerDependency of 5.0.0, this is not a typing issue with PixiJS but a mix of v5 and v6 packages as a result of that dependency's peer. I'm going to close this an open a new issue on pixi-svg.

**Comment by gterminator** [comment]
problem still persist with 7.2.4.

After trying 4 hours to get everything around with typescript. 

**I just deleted pixijs. For everyone Googleing this. Please delete it too. It will save your lifetime.**

It's sad but it is too instabile and the documentation is not up to date (there are methods mentioned in Container that not exist). 
Example: onglobalmousemove on Container.
It not exists on Typescript 7.2.4
- Tried several additional "mixed ins" not event the install of the EventSystem works.

Maybe we should stay in plain javascript. This is just not typescript "ready".

**Comment by bigtimebuddy** [comment]
@gterminator  Sorry you're having issues with your TypeScript environment. Could you please provide a simple repo that reproduces your error? That would help more than telling people to avoid the project.

**Comment by gterminator** [comment]
@bigtimebuddy I'm very sorry, I've fixed it.

The issue was that I'm using angular and was setting the 

`   
 "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
`
in angularCompilerOptions instead of compilerOptions.

Sorry again.
