### ISSUE TITLE
Bug: why is there not exist function "getChildByName" in my Container

### ISSUE THREAD

**Issue by shifangwang11** [pixijs/pixijs#9620]
### Current Behavior

I update pixi from 6.4.2 to 7.2.4.Then I found that the "getChildByname" function is invalid.
For example:
`const nodeContainer = new PIXI.Container();`
`nodeContainer.getChildByName()`
<img width="629" alt="image" src="https://github.com/pixijs/pixijs/assets/52688953/13d6bf71-98b4-42cf-8128-36a760509d4a">
so I find PIXI Class. There is not exist function "getChildByName" in PIXI.Container
<img width="460" alt="image" src="https://github.com/pixijs/pixijs/assets/52688953/701c77f3-4f4f-4936-a821-4837e62b3b60">

### Expected Behavior

<img width="1075" alt="image" src="https://github.com/pixijs/pixijs/assets/52688953/91fff4fb-8f39-4d96-be9b-870a9b58eeb9">

### Steps to Reproduce

I feel weird.And my English is not very good. I wonder if the description is clear?

### Environment

- **`pixi.js` version**: *e.g. 7.2.4*
- **Browser & Version**: *e.g. Chrome 116*
- **OS & Version**: *e.g. macOS Big Sur 11.1 *

**Comment by SuperSodaSea** [comment]
Which way do you import Pixi.js?
你是用什么方式导入 Pixi.js 的？

**Comment by shifangwang11** [comment]
npm install pixi.js
import * as PIXI from "pixi.js"

**Comment by SuperSodaSea** [comment]
Using webpack?

**Comment by shifangwang11** [comment]
my project build by vue2，vue-cli

**Comment by SuperSodaSea** [comment]
I tried to create a new project using vue-cli + vue2 and everything looks fine (`getChildByName` exists). Could you create a small project that reproduces your problem and upload it to GitHub?

**Comment by shifangwang11** [comment]
Thank you very much.I will try to create a small project for verification

**Comment by bigtimebuddy** [comment]
Please also read [this](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) for upgrading. It's important to inspect your **package-lock.json** to make sure it's _only_ v7 PixiJS dependencies (look for `@pixi/*` packages).

**Comment by shifangwang11** [comment]
Thank you very much. I try !

**Comment by shifangwang11** [comment]
I uninstall pixi.js and install pixi.js(7.2.4).There is still has problem.So I create a new project using vue-cli + vue2 and install pixi.js.There has same problem too(getChildByName is not found in PIXI.Container).

I notice a previous problem.When I install pixi.js and start vue project.There is a error.Please see a picture below.
<img width="1164" alt="image" src="https://github.com/pixijs/pixijs/assets/52688953/cd8f20aa-07ce-4078-b313-2d5b4ca2b2ba">
It is look like load .mjs file has problem.
So I add some code in vue.config.js.
<img width="424" alt="image" src="https://github.com/pixijs/pixijs/assets/52688953/dc733baf-8828-4b3d-b160-87d1c95efe8b">
Is it possible that this code is causing the problem(getChildByName is not found in PIXI.Container)?

If yes, how can I solve the .mjs loading problem.


> I tried to create a new project using vue-cli + vue2 and everything looks fine (`getChildByName` exists). Could you create a small project that reproduces your problem and upload it to GitHub?



> Please also read [this](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) for upgrading. It's important to inspect your **package-lock.json** to make sure it's _only_ v7 PixiJS dependencies (look for `@pixi/*` packages).

**Comment by shifangwang11** [comment]
My nodejs version is v16.13.1，npm v8.1.2

**Comment by shifangwang11** [comment]
I try to import pixi.js by `<script src="https://pixijs.download/release/pixi.js"></script>`.The Container has `getChildByName` function.So maybe the problem comes from node version? npm version? webpack version? vue-cli version?

**Comment by SuperSodaSea** [comment]
> So I create a new project using vue-cli + vue2 and install pixi.js.There has same problem too(getChildByName is not found in PIXI.Container).

Could you upload this project, so that we can locate the problem faster?

**Comment by shifangwang11** [comment]
Hello! This is my demo URL [https://github.com/shifangwang11/my-pixi-demo](url) Please help me.

**Comment by SuperSodaSea** [comment]
@shifangwang11 Seems that the problem is caused by using an old version of `@vue/cli`. You can use the following command to update your `@vue/cli` and `@vue/cli-*` packages in your project:

```bash
# Update global @vue/cli
npm up -g
# Update project @vue/cli-*
npm i -D --force @vue/cli-plugin-babel@5 @vue/cli-plugin-eslint@5 @vue/cli-service@5 eslint@7 eslint-plugin-vue@8
```

Then you will find the `getChildByName` is no longer `undefined`, and you will not need the `config.chainWebpack` & `config.transpileDependencies` code in your `vue.config.js` anymore.

---

(For those interested, using an older version of `@vue/cli` seems to cause Webpack to bundle both *.js and *.mjs version of the packages in PixiJS. For some unknown reason `pixi.js` package exports `.js` version of `@pixi/display`, while `@pixi/mixin-get-child-by-name` modifies `.mjs` version of `@pixi/display`, so  `getChildByName` will no appear on `PIXI.Container`.)

**Comment by shifangwang11** [comment]
Thank you very much.I update my @vue/cli version then this problem is solved.I still need to learn more about webpack.Thank you again for your answer

**Comment by CrazyFlasher** [comment]
I receive the same error:
```
TypeError: this._assets.getChildByName is not a function
```
Using
```
"@pixi/ui": "0.9.0",
"@pixi/animate": "3.0.0",
pixi.js": "7.2.4",
"esbuild": "0.19.3"
```
Building with `esbuild`
Node: 18.18.0
Npm: 10.1.0

**Comment by CrazyFlasher** [comment]
Works fine with `"pixi.js": "7.3.1"`

**Comment by bigtimebuddy** [comment]
This can happen if you have multiple versions of pixi installed as a result of peer dependencies between plugins (check your package-lock.json for multiple `@pixi/*` versions). Please reference this https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS if are still having issues, please open a new issue with a reproduction.
